apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: andy-wang-asg2-
spec:
  pipelineRef:
name: andy-wang-pipeline
  workspaces:
     name: pipeline-shared-data
        PersistentVolumeClaim:
          claimName: andy-wang-pvc
